import type { FreeReportData } from './hooks/useAnalysis'

export const mockFreeReport: FreeReportData = {
  score: 62,
  summary:
    'Din hemsida har en okej teknisk grund men saknar flera viktiga signaler för AI-sökmotorer. LocalBusiness-schema och llms.txt saknas helt, vilket gör att AI:n har svårt att förstå vem du är och vad du gör.',
  categories: {
    technical: { score: 7, label: 'Teknisk grund' },
    local: { score: 4, label: 'Lokal synlighet' },
    aireadiness: { score: 3, label: 'AI-beredskap' },
    content: { score: 6, label: 'Innehåll' },
  },
  phases: [
    {
      id: 'technical',
      label: 'Teknisk grund',
      checks: [
        {
          title: 'HTTPS/SSL',
          status: 'good',
          finding: 'Sidan använder HTTPS med giltigt certifikat.',
          what: 'HTTPS krypterar all trafik mellan besökarens webbläsare och din server.',
          why: 'AI-sökmotorer och användare litar mer på säkra sidor — osäkra sidor rankas lägre.',
          fix: '',
        },
        {
          title: 'Robots.txt',
          status: 'good',
          finding: 'robots.txt finns och är korrekt konfigurerad.',
          what: 'Robots.txt är en textfil som talar om för sökmotorer vilka sidor de får besöka.',
          why: 'Utan robots.txt kan AI-crawlers missförstå din webbplats eller undvika att indexera viktigt innehåll.',
          fix: '',
        },
        {
          title: 'Sitemap.xml',
          status: 'warning',
          finding: 'Ingen sitemap.xml hittades.',
          what: 'Sitemap.xml är en fil som listar alla viktiga sidor på din webbplats.',
          why: 'AI-crawlers använder sitemaps för att snabbare hitta och förstå strukturen på din webbplats.',
          fix: 'Skapa en sitemap.xml och registrera den i Google Search Console.',
        },
        {
          title: 'LLMS.TXT',
          status: 'bad',
          finding: 'Ingen llms.txt hittades.',
          what: 'llms.txt är en ny standard där du kan beskriva din webbplats specifikt för AI-modeller.',
          why: 'Med llms.txt kan du styra exakt hur AI-crawlers tolkar och använder ditt innehåll.',
          fix: 'Skapa /llms.txt med en kort beskrivning av din verksamhet.',
        },
        {
          title: 'Sidhastighet / Core Web Vitals',
          status: 'warning',
          finding: 'Servern svarar men sidhastighet kunde inte bedömas från tillgänglig data.',
          what: 'Core Web Vitals mäter laddningstid, interaktivitet och visuell stabilitet.',
          why: 'Långsamma sidor rankas lägre — AI-motorer prioriterar sidor som ger användaren snabba svar.',
          fix: 'Optimera bilder, minifiera CSS/JS och överväg CDN.',
        },
        {
          title: 'Canonical tags',
          status: 'good',
          finding: 'Canonical tags finns på sidorna.',
          what: 'Canonical tags talar om för sökmotorer vilken version av en sida som är den ursprungliga.',
          why: 'Förhindrar duplicerat innehåll och hjälper AI att förstå vilken sida som ska indexeras.',
          fix: '',
        },
      ],
    },
    {
      id: 'local',
      label: 'Lokal synlighet',
      checks: [
        {
          title: 'NAP (Name, Address, Phone) på hemsidan',
          status: 'warning',
          finding: 'Telefonnummer hittades: 031-123 45 67, men adress är ofullständig.',
          what: 'NAP står för Name, Address, Phone — dina grundläggande företagsuppgifter.',
          why: 'AI-motorer använder NAP för att verifiera att du är ett riktigt lokalt företag — felaktiga uppgifter sänker synligheten.',
          fix: 'Lägg till företagsnamn, fullständig adress och telefonnummer tydligt på sidan, helst i sidfoten.',
        },
        {
          title: 'Telefonnummer synligt',
          status: 'good',
          finding: 'Telefonnummer finns tydligt på kontaktsidan.',
          what: 'Ett synligt telefonnummer gör det enkelt för kunder att kontakta dig.',
          why: 'AI-motorer prioriterar företag med tydliga kontaktvägar — det signalerar trovärdighet.',
          fix: '',
        },
        {
          title: 'Ort / stad nämns på sidan',
          status: 'good',
          finding: 'Göteborg nämns i titel, H1 och brödtext.',
          what: 'Att nämna orten tydligt visar var ditt företag finns.',
          why: 'Lokala sökningar som "tandläkare Göteborg" matchar bättre när orten finns på sidan.',
          fix: '',
        },
        {
          title: 'Google Maps embed eller länk',
          status: 'bad',
          finding: 'Ingen Google Maps embed eller länk hittades.',
          what: 'Google Maps embed eller länk visar var ditt företag finns på en karta.',
          why: 'AI-motorer använder kartdata för att verifiera din plats och visa dig i lokala sökresultat.',
          fix: 'Bädda in en Google Maps-karta på kontaktsidan med din adress.',
        },
        {
          title: 'LocalBusiness schema',
          status: 'bad',
          finding: 'Inget LocalBusiness-schema hittades.',
          what: 'LocalBusiness Schema är strukturerad data (JSON-LD) som beskriver ditt företag för sökmotorer.',
          why: 'AI-motorer använder schema för att direkt extrahera öppettider, adress och telefon utan att tolka texten.',
          fix: 'Lägg till LocalBusiness JSON-LD schema med namn, adress, telefon och öppettider.',
        },
        {
          title: 'Öppettider på hemsidan',
          status: 'warning',
          finding: 'Öppettider finns men är svåra att hitta.',
          what: 'Tydliga öppettider hjälper kunder att veta när de kan besöka eller ringa dig.',
          why: 'AI-motorer använder öppettider för att svara på "är de öppna nu"-frågor.',
          fix: 'Lägg till öppettider tydligt på kontaktsidan med schema markup.',
        },
      ],
    },
    {
      id: 'aireadiness',
      label: 'AI-beredskap',
      checks: [
        {
          title: 'Schema markup (någon typ)',
          status: 'bad',
          finding: 'Ingen schema markup hittades på någon sida.',
          what: 'Schema markup är strukturerad data som hjälper sökmotorer att förstå ditt innehåll.',
          why: 'Utan schema markup måste AI gissa vad din sida handlar om — du missar chansen att synas i AI-svar.',
          fix: 'Lägg till schema.org markup, t.ex. Organization eller LocalBusiness.',
        },
        {
          title: 'LocalBusiness eller Restaurant schema',
          status: 'bad',
          finding: 'Inget LocalBusiness eller Restaurant-schema hittades.',
          what: 'LocalBusiness-schema beskriver ditt företag för sökmotorer med adress, telefon och öppettider.',
          why: 'AI-motorer citerar och visar schema-data direkt i sökresultaten — utan det syns du inte.',
          fix: 'Lägg till LocalBusiness JSON-LD i <head> på din sida.',
        },
        {
          title: 'JSON-LD format',
          status: 'bad',
          finding: 'Ingen JSON-LD hittades — ingen schema markup alls.',
          what: 'JSON-LD är det rekommenderade formatet för schema markup, inbäddat i <script>-taggar.',
          why: 'Google och andra AI-motorer föredrar JSON-LD framför andra schema-format.',
          fix: 'Använd JSON-LD-formatet för all schema markup: <script type="application/ld+json">.',
        },
        {
          title: 'AI-optimerad meta-beskrivning',
          status: 'warning',
          finding: 'Meta description finns (142 tecken) men är för generisk.',
          what: 'En AI-optimerad meta-beskrivning är koncis, informativ och innehåller nyckelord.',
          why: 'AI-motorer använder meta description för att generera förhandsvisningar och svar.',
          fix: 'Skriv en meta description på 120-160 tecken som tydligt beskriver vad du erbjuder och var.',
        },
        {
          title: 'Semantisk HTML-struktur',
          status: 'good',
          finding: 'Sidan använder semantiska taggar (header, nav, main, footer).',
          what: 'Semantisk HTML använder rätt taggar för rätt innehåll istället för generiska div:ar.',
          why: 'AI-crawlers använder semantisk struktur för att förstå hierarki och viktigt innehåll.',
          fix: '',
        },
      ],
    },
    {
      id: 'content',
      label: 'Innehåll',
      checks: [
        {
          title: 'H1-tagg (finns och är unik per sida)',
          status: 'good',
          finding: 'H1: "Tandläkare Johansson — Din tandläkare i Göteborg" — tydlig och unik.',
          what: 'H1 är huvudrubriken på sidan och ska beskriva sidans innehåll.',
          why: 'AI-motorer använder H1 för att förstå vad sidan handlar om — en svag H1 sänker relevansen.',
          fix: '',
        },
        {
          title: 'Title-tagg (optimal längd)',
          status: 'warning',
          finding: "Title: 'Tandläkare Johansson' (34 tecken) — för kort.",
          what: 'Title-tagg visas i sökresultaten och ska vara 30-60 tecken.',
          why: 'En för kort title missar chansen att inkludera viktiga nyckelord och locka klick.',
          fix: 'Byt till "Tandläkare Johansson i Göteborg | Torslanda | Akut tandvård"',
        },
        {
          title: 'Meta description',
          status: 'warning',
          finding: 'Meta description finns men är för generisk och saknar CTA.',
          what: 'Meta description är den text som visas under titeln i sökresultaten.',
          why: 'En bra meta description ökar klickfrekvensen och hjälper AI att förstå sidans innehåll.',
          fix: 'Skriv en unik meta description för varje sida med nyckelord och en call-to-action.',
        },
        {
          title: 'Alt-texter på bilder',
          status: 'warning',
          finding: 'Vissa bilder saknar alt-texter eller har generiska namn.',
          what: 'Alt-texter beskriver bilder för skärmläsare och sökmotorer.',
          why: 'AI-motorer kan inte "se" bilder — de läser alt-texter för att förstå bildinnehåll.',
          fix: 'Lägg till beskrivande alt-texter på alla bilder, inklusive nyckelord där det är naturligt.',
        },
        {
          title: 'Internlänkning',
          status: 'good',
          finding: 'Sidan har god internlänkning mellan relaterade sidor.',
          what: 'Internlänkning är länkar mellan sidor på samma webbplats.',
          why: 'AI-motorer använder internlänkar för att förstå webbplatsens struktur och hitta allt innehåll.',
          fix: '',
        },
        {
          title: 'Språk (svenska vs engelska)',
          status: 'good',
          finding: 'Sidan är på svenska med korrekt lang="sv" attribut.',
          what: 'Att deklarera rätt språk hjälper sökmotorer att matcha din sida med rätt användare.',
          why: 'AI-motorer använder språkdeklarationen för att visa ditt innehåll för rätt målgrupp.',
          fix: '',
        },
      ],
    },
  ],
  criticalIssues: [
    {
      severity: 'high',
      category: 'local',
      title: 'LocalBusiness-schema saknas',
      description:
        'Din sida har inget LocalBusiness-schema. Detta är den viktigaste signalen för lokal AI-synlighet.',
      fix: 'Lägg till följande JSON-LD i <head>:',
      codeExample: `<script type="application/ld+json">
{
  "@context": "https://schema.org",
  "@type": "Dentist",
  "name": "Tandläkare Johansson",
  "address": {
    "@type": "PostalAddress",
    "streetAddress": "Torslandavägen 12",
    "addressLocality": "Göteborg",
    "addressRegion": "Västra Götalands län",
    "postalCode": "423 38",
    "addressCountry": "SE"
  },
  "telephone": "+46-31-123-45-67",
  "url": "https://tandlakare-johansson.se"
}
</script>`,
    },
    {
      severity: 'medium',
      category: 'content',
      title: 'Ortnamn saknas i title och H1',
      description:
        'Lokala sökningar matchar bättre när orten finns med i titel och rubriker.',
      fix: 'Byt title till "Tandläkare Johansson — Göteborg | Torslanda" och H1 till "Din tandläkare i Göteborg".',
      codeExample: null,
    },
  ],
  quickWins: [
    {
      title: 'Skapa en sitemap.xml',
      fix: 'Generera en sitemap.xml med alla dina sidor och lägg den i roten på domänen.',
      effort: 'small',
    },
    {
      title: 'Lägg till FAQ-sektion',
      fix: 'Skapa en sida med 5-10 vanliga frågor och svar om dina tjänster.',
      effort: 'small',
    },
  ],
  localSignals: {
    napFound: true,
    cityFound: true,
    cityName: 'Göteborg',
    hasLocalBusinessSchema: false,
    hasRestaurantSchema: false,
    schemaType: null,
    languageWarning: null,
    pagesScanned: 5,
  },
}
